os:
  - linux
  - osx
language: node_js
node_js:
  - "7"
  - "6"
  - "6.6.0"
  - "6.5.0"
install:
  - npm install
script:
  - npm start
  - electron-packager . FairChair --platform=darwin --arch=x64 --prune —icon=omun.icns
