language: node_js
node_js:
  - 7
  - 8

os:
# - linux
- osx

install:
  - npm install -g electron-forge
  - npm install

jobs:
  include:
    - stage: test
      script: npm run make
    - stage: deploy
      if: branch = stable
      script: npm run publish
