os:
  - osx
# addons:
#   apt:
#     packages:
#       - xvfb
# language: node_js
node_js:
  - "7.4.0"
install:
#   - export DISPLAY=':99.0'
#   - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - npm install -g electron
  - npm install -g electron-packager
script:
  - "npm run build-osx"
