language: node_js

os:
  - osx

install:
  - npm install -g electron-forge
  - npm install

jobs:
  include:
    - stage: test
      node_js: 8
      script: npm run make
    - stage: deploy
      if: branch = stable
      node_js: 8
      script: npm run publish
