os:
  - linux
  - osx
node_js:
  - "6.6.0"
install:
  - npm install
  - npm install -g electron
  - npm install -g electron-packager
script:
  - npm start
# - electron-packager . FairChair --platform=darwin --arch=x64 --prune —icon=omun.icns
