notifications:
  email:
    on_success: never
    on_failure: change

language: node_js
node_js: 8


install:
  - npm install

matrix:
  include:
  - os: osx
    script:
      - npm run make
      - npm run make-mas
  - os: linux
    script:
      - npm run make

jobs:
  include:
    - stage: test
      node_js: 8
      script: npm run make
      script: npm run make-mas
    - stage: deploy
      if: branch = stable
      os: osx
      node_js: 8
      script: npm run publish
